---
# Source: application/templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  labels:
    app: common-service
    group: com.stakater.platform
    provider: stakater
    version: "1.0.0"
    chart: "application-1.0.0"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: common-service
data:
  secretKey1: c2VjcmV0VmFsdWUx
  secretKey2: c2VjcmV0VmFsdWUy
---
# Source: application/templates/configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: common-service
    group: com.stakater.platform
    provider: stakater
    version: "1.0.0"
    chart: "application-1.0.0"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: common-service
data:
  key1: value1
  key2: value2
  
---
# Source: application/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: common-service
    group: com.stakater.platform
    provider: stakater
    version: "1.0.0"
    chart: "application-1.0.0"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: common-service
---
# Source: application/templates/role.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: common-service
    group: com.stakater.platform
    provider: stakater
    version: "1.0.0"
    chart: "application-1.0.0"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: common-service-role-configmaps
rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - get
  
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: common-service
    group: com.stakater.platform
    provider: stakater
    version: "1.0.0"
    chart: "application-1.0.0"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: common-service-role-secrets
rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
  
---
# Source: application/templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  labels:
    app: common-service
    group: com.stakater.platform
    provider: stakater
    version: "1.0.0"
    chart: "application-1.0.0"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: common-service
spec:
  selector:
    app: common-service
    
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    
---
# Source: application/templates/deployment.yaml

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: common-service
    group: com.stakater.platform
    provider: stakater
    version: "1.0.0"
    chart: "application-1.0.0"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: common-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: common-service
        
    spec:
      containers:
      - name: common-service
        image: "stakater/application:1.0.0"    
        imagePullPolicy: IfNotPresent
      serviceAccountName: common-service        
