{{- if .Values.alertmanagerConfig -}}
{{- if .Values.alertmanagerConfig.enabled -}}
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: {{ template "application.name" . }}
  namespace: {{ template "application.namespace" . }}
  labels:
{{ toYaml .Values.alertmanagerConfig.selectionLabels | indent 4 }}
spec:
{{ toYaml .Values.alertmanagerConfig.spec | indent 4 }}