{{- if (.Values.backup).enabled }}
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: {{ printf "%s-backup" .Values.applicationName | trunc 63 | quote }}
  namespace: {{ .Values.backup.namespace | quote }}
spec:
  includedNamespaces:
    - {{ printf "%s" .Release.Namespace | quote }}
  snapshotVolumes: {{ .Values.backup.snapshotVolumes }}
  storageLocation: {{ .Values.backup.storageLocation | quote }}
  ttl: {{ .Values.backup.ttl }}
  includedResources:
{{ toYaml .Values.backup.includedResources | indent 4 }}
  excludedResources:
{{ toYaml .Values.backup.excludedResources | indent 4 }}
{{- end }}
