{{- if (.Values.backup).enabled }}
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: {{ .Values.backup.backupCRName }}
  namespace: openshift-adp
spec:
  includedNamespaces:
    - {{ .Values.backup.includedNamespaces | quote }}
  snapshotVolumes: {{ .Values.backup.snapshotVolumes }}
  storageLocation: {{ .Values.backup.storageLocation | quote }}
  ttl: {{ .Values.backup.ttl }}
  includeResources:
{{ toYaml (.Values.backup).includedResources | indent 4 }}
  excludeResources:
{{ toYaml (.Values.backup).excludedResources | indent 4 }}
{{- end }}
