{{- if .Values.prometheusRule -}}
{{- if .Values.prometheusRule.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
{{- if .Values.prometheusRule.labels -}}
  labels:
{{ toYaml .Values.prometheusRule.labels | indent 4 }}
{{- end -}}
  name: {{ template "application.name" . }}
  namespace: {{ template "application.namespace" . }}
spec:
  groups:
{{ toYaml .Values.prometheusRule.groups | indent 4 }}
{{- end -}}
{{- end -}}