{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "application.name" . }}
  labels:
{{ include "application.labels.stakater" . | indent 4 }}
{{ include "application.labels.chart" . | indent 4 }}
{{- if .Values.route.additionalLabels }}
{{ toYaml .Values.route.additionalLabels | indent 4 }}
{{- end }}
{{- if .Values.route.annotations }}
  annotations:
{{ toYaml .Values.route.annotations | indent 4 }}
{{- end }}
spec:
  host: {{ .Values.route.host }}
  port:
{{ toYaml .Values.route.port | indent 4 }}
  termination: {{ .Values.route.termination }}
  to:
    kind: {{ .Values.route.to.kind }}
    name: {{ .Values.route.to.name }}
    weight: {{ .Values.route.to.weight }}
{{- if .Values.route.wildcardPolicy }}
  wildcardPolicy: {{ .Values.route.wildcardPolicy }}
{{- end -}}
  {{- if .Values.route.tls }}
  tls:
{{ toYaml .Values.route.tls | indent 4 }}
  {{- end -}}
{{- end -}}
