{{- if and .Values.secret .Values.secret.data }}
apiVersion: v1
kind: Secret
metadata:
  labels:
{{ include "application.labels.stakater" . | indent 4 }}
{{ include "application.labels.chart" . | indent 4 }}
{{- if .Values.secret.additionalLabels }}
{{ toYaml .Values.secret.additionalLabels | indent 4 }}
{{- end }}
{{- if .Values.secret.annotations }}
  annotations:
{{ toYaml .Values.secret.annotations | indent 4 }}
{{- end }}
  name: {{ template "application.name" . }}
data:
{{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}