name: Pull Request

on:
  pull_request_target:
    branches:
      - master
    paths-ignore:
    - 'README.md'

env:
  CHART_NAME: "application"

jobs:
  build:
    name: Build
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: sno2

    steps:

    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{github.event.pull_request.head.sha}}

    # Set Up Helm
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.8.2

    # Lint
    - name: Helm Lint
      run: |
        helm lint ${CHART_NAME}

    # Dry run to ensure that manifests are generated successfully
    - name: Dry Run Chart
      run: |
        helm install ${CHART_NAME} ${CHART_NAME} -f ${CHART_NAME}/values-test.yaml -n stakater-chart-pipeline-test --dry-run --debug

    - name: Comment on PR
      uses: mshick/add-pr-comment@v2
      env:
        GITHUB_TOKEN: ${{ secrets.STAKATER_GITHUB_TOKEN }}
      with:
        message-success: '@${{ github.actor }} validation successful`'
        message-failure: '@${{ github.actor }} Yikes! You better fix it before anyone else finds out! [Build](https://github.com/${{ github.repository }}/commit/${{ github.event.pull_request.head.sha }}/checks) has Failed!'
        allow-repeats: false

    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      if: always() # Pick up events even if the job fails or is canceled.
      with:
        status: ${{ job.status }}
        fields: repo,author,action,eventName,ref,workflow
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.STAKATER_DELIVERY_SLACK_WEBHOOK }}
  
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: d3adb5/helm-unittest-action@v1
        with:
          charts: application
