name: Pull Request

on:
  push:
    branches:
     - issue/fix-github-actions
  pull_request_target:
    branches:
      - master
    paths-ignore:
    - 'README.md'

env:
  CHART_NAME: "application"

jobs:
  build:
    runs-on: ubuntu-latest 
    name: Build
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"    

    steps:

    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{github.event.pull_request.head.sha}}

    - name: Authenticate to OC cluster
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.STAKATER_TEST_CLUSTER }}
        openshift_username: ${{ secrets.STAKATER_TEST_USER }}
        openshift_password: ${{ secrets.STAKATER_TEST_PASSWORD }}

    # Set Up Helm
    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.4.0

    # Lint
    - name: Helm Lint
      run: |
        helm lint ${CHART_NAME}

    # Dry run to ensure that manifests are generated successfully 
    - name: Dry Run Chart
      run: |
        kubectl create ns pipeline-test
        helm install ${CHART_NAME} ${CHART_NAME} -f ${CHART_NAME}/values-test.yaml -n pipeline-test --dry-run --debug
        kubectl delete ns pipeline-test
    # package
    - name: Helm Package
      run: |
        helm package ${CHART_NAME}    

    - name: Comment on PR
      uses: mshick/add-pr-comment@v1
      env:
        GITHUB_TOKEN: ${{ secrets.STAKATER_GITHUB_TOKEN }}
      with:
        message: '@${{ github.actor }} Validation Successful'
        allow-repeats: false

    - name: Notify Failure
      if: failure()
      uses: mshick/add-pr-comment@v1
      env:
        GITHUB_TOKEN: ${{ secrets.STAKATER_GITHUB_TOKEN }}
      with:
        message: '@${{ github.actor }} Yikes! You better fix it before anyone else finds out! [Build](https://github.com/${{ github.repository }}/commit/${{ github.event.pull_request.head.sha }}/checks) has Failed!'
        allow-repeats: false

    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      if: always() # Pick up events even if the job fails or is canceled.
      with:
        status: ${{ job.status }}
        fields: repo,author,action,eventName,ref,workflow
      env:
        GITHUB_TOKEN: ${{ secrets.STAKATER_GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.STAKATER_DELIVERY_SLACK_WEBHOOK }}
  
